const cards= [
    {name: 'Item 1', description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took ', image: 'https://muzkom.com.ua/uploads/images/photo/22425/FENDER-Deluxe-Active-Jazz-Bass-MN-5.jpg', hasColors: true, sizes: ['xl', 'l'], colors: ['red', 'green', 'blue'], keywords: ['red', 'green', 'blue', 'xl', 'l'], price: 12210},
    {name: 'Item 2', description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s', image: 'https://cdn.shoplightspeed.com/shops/651790/files/40251658/1652x1652x1/fender-1965-fender-jazz-bass-olympic-white-refinis.jpg', hasColors: true, sizes: ['m'], colors: ['red'], keywords: ['red', 'm'], price: 13420},
    {name: 'Item 3 long name vary long name', description: 'description', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQR5zpQoyewAxksRHm61aWS7JpqQE11tp-6F5DWUJ6oNt0la6_G3BlmFrTEkd7woWVGMVY&usqp=CAU', hasColors: true, sizes: ['xl', 'l'], colors: ['green'], keywords: ['green', 'xl', 'l'], price: 11300},
    {name: 'Item 4 long name vary long name long name vary long name long name vary long name', description: 'description', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQR5zpQoyewAxksRHm61aWS7JpqQE11tp-6F5DWUJ6oNt0la6_G3BlmFrTEkd7woWVGMVY&usqp=CAU', hasColors: true, sizes: ['xl', 'l'], colors: ['green'], keywords: ['green', 'xl', 'l'], price: 13120},
    {name: 'Item 2', description: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of', image: 'https://static.nike.com/a/images/q_auto:eco/t_product_v1/f_auto/dpr_3.0/w_300,c_limit/4f37fca8-6bce-43e7-ad07-f57ae3c13142/air-force-1-07-mens-shoes-5QFp5Z.png', hasColors: true, sizes: ['m'], colors: ['red'], keywords: ['red', 'm'], price: 13400},
    {name: 'Item 3 long name vary long name', description: 'description', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQR5zpQoyewAxksRHm61aWS7JpqQE11tp-6F5DWUJ6oNt0la6_G3BlmFrTEkd7woWVGMVY&usqp=CAU', hasColors: true, sizes: ['xl', 'l'], colors: ['green'], keywords: ['green', 'xl', 'l'], price: 10340},
    {name: 'Item 2', description: 'description', image: 'https://static.nike.com/a/images/q_auto:eco/t_product_v1/f_auto/dpr_3.0/w_300,c_limit/4f37fca8-6bce-43e7-ad07-f57ae3c13142/air-force-1-07-mens-shoes-5QFp5Z.png', hasColors: true, sizes: ['m'], colors: ['red'], keywords: ['red', 'm'], price: 13271},
    {name: 'Item 3 long name vary long name', description: 'description', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQR5zpQoyewAxksRHm61aWS7JpqQE11tp-6F5DWUJ6oNt0la6_G3BlmFrTEkd7woWVGMVY&usqp=CAU', hasColors: true, sizes: ['xl', 'l'], colors: ['green'], keywords: ['green', 'xl', 'l'], price: 12320}

]

export default cards;